/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <mex.h>
#include <stdio.h>
#include <string.h>


#ifndef ulong
#  define ulong unsigned long
#endif
#ifndef uint
#  define uint  unsigned int
#endif
#ifndef uchar
#  define uchar unsigned char
#endif


/*
 * Support for 32-bit and 64-bit MEX files
 */
#ifndef mwSize
#  define mwSize int
#endif
#ifndef mwIndex
#  define mwIndex int
#endif
#ifndef mwSignedIndex
#  define mwSignedIndex int
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;


/*
 * Support routines for copying data into and out of the MEX stubs
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
    mxArray* ap;
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        sprintf(pbuf, fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    mwSize slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}

/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_mwIndex, mwIndex)
mxWrapCopyDef    (mxWrapCopy_mwIndex,     mwIndex)
mxWrapReturnDef  (mxWrapReturn_mwIndex,   mwIndex)
mxWrapGetArrayDef(mxWrapGetArray_mwSignedIndex, mwSignedIndex)
mxWrapCopyDef    (mxWrapCopy_mwSignedIndex,     mwSignedIndex)
mxWrapReturnDef  (mxWrapReturn_mwSignedIndex,   mwSignedIndex)
mxWrapGetArrayDef(mxWrapGetArray_mwSize, mwSize)
mxWrapCopyDef    (mxWrapCopy_mwSize,     mwSize)
mxWrapReturnDef  (mxWrapReturn_mwSize,   mwSize)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef(mxWrapGetArray_uchar, uchar)
mxWrapCopyDef    (mxWrapCopy_uchar,     uchar)
mxWrapReturnDef  (mxWrapReturn_uchar,   uchar)
mxWrapGetArrayDef(mxWrapGetArray_uint, uint)
mxWrapCopyDef    (mxWrapCopy_uint,     uint)
mxWrapReturnDef  (mxWrapReturn_uint,   uint)
mxWrapGetArrayDef(mxWrapGetArray_ulong, ulong)
mxWrapCopyDef    (mxWrapCopy_ulong,     ulong)
mxWrapReturnDef  (mxWrapReturn_ulong,   ulong)

/* ---- gluttonfit.mw: 34 ----
 * smartscore(double[] W, int M, int T, int K, int fac, double[] Y, int Nt, double[] tsh, int Nsh, output double[K, Nsh] S, double eta, int skip);
 */
const char* stubids1_ = "smartscore(i double[], i int, i int, i int, i int, i double[], i int, i double[], i int, o double[xx], i double, i int)";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* W          */
    int         in1_;    /* M          */
    int         in2_;    /* T          */
    int         in3_;    /* K          */
    int         in4_;    /* fac        */
    double*     in5_ =0; /* Y          */
    int         in6_;    /* Nt         */
    double*     in7_ =0; /* tsh        */
    int         in8_;    /* Nsh        */
    double      in9_;    /* eta        */
    int         in10_;    /* skip       */
    double*     out0_=0; /* S          */
    mwSize      dim11_;   /* K          */
    mwSize      dim12_;   /* Nsh        */

    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    in6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    in8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in9_ = (double) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    out0_ = (double*) mxMalloc(dim11_*dim12_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[1]++;
    smartscore(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, out0_, in9_, in10_);
    plhs[0] = mxCreateDoubleMatrix(dim11_, dim12_, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim11_*dim12_);

mw_err_label:
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- gluttonfit.mw: 37 ----
 * fillscore(double[] W, int M, int T, int K, int fac, double[] Y, int Nt, double[] tsh, int Nsh, output double[K, Nsh] S, double eta, int[] shflags);
 */
const char* stubids2_ = "fillscore(i double[], i int, i int, i int, i int, i double[], i int, i double[], i int, o double[xx], i double, i int[])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* W          */
    int         in1_;    /* M          */
    int         in2_;    /* T          */
    int         in3_;    /* K          */
    int         in4_;    /* fac        */
    double*     in5_ =0; /* Y          */
    int         in6_;    /* Nt         */
    double*     in7_ =0; /* tsh        */
    int         in8_;    /* Nsh        */
    double      in9_;    /* eta        */
    int*        in10_ =0; /* shflags    */
    double*     out0_=0; /* S          */
    mwSize      dim11_;   /* K          */
    mwSize      dim12_;   /* Nsh        */

    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    in6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    in8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in9_ = (double) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxWrapGetArray_int(prhs[10], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in10_ = NULL;
    out0_ = (double*) mxMalloc(dim11_*dim12_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[2]++;
    fillscore(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, out0_, in9_, in10_);
    plhs[0] = mxCreateDoubleMatrix(dim11_, dim12_, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim11_*dim12_);

mw_err_label:
    if (out0_) mxFree(out0_);
    if (in10_)  mxFree(in10_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- gluttonfit.mw: 59 ----
 * locvalidmins(double[] S, int K, int Nsh, double[] nlps, inout int[] jt, inout int[] l, inout double[] s, output int[1] Nmin);
 */
const char* stubids3_ = "locvalidmins(i double[], i int, i int, i double[], io int[], io int[], io double[], o int[x])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* S          */
    int         in1_;    /* K          */
    int         in2_;    /* Nsh        */
    double*     in3_ =0; /* nlps       */
    int*        in4_ =0; /* jt         */
    int*        in5_ =0; /* l          */
    double*     in6_ =0; /* s          */
    int*        out3_=0; /* Nmin       */
    mwSize      dim7_;   /* 1          */

    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    out3_ = (int*) mxMalloc(dim7_*sizeof(int));
    if (mexprofrecord_)
        mexprofrecord_[3]++;
    locvalidmins(in0_, in1_, in2_, in3_, in4_, in5_, in6_, out3_);
    plhs[0] = mxCreateDoubleMatrix(mxGetM(prhs[4]), mxGetN(prhs[4]), mxREAL);
    mxWrapCopy_int(plhs[0], in4_, mxGetM(prhs[4])*mxGetN(prhs[4]));
    plhs[1] = mxCreateDoubleMatrix(mxGetM(prhs[5]), mxGetN(prhs[5]), mxREAL);
    mxWrapCopy_int(plhs[1], in5_, mxGetM(prhs[5])*mxGetN(prhs[5]));
    plhs[2] = mxCreateDoubleMatrix(mxGetM(prhs[6]), mxGetN(prhs[6]), mxREAL);
    mxWrapCopy_double(plhs[2], in6_, mxGetM(prhs[6])*mxGetN(prhs[6]));
    plhs[3] = mxCreateDoubleMatrix(dim7_, 1, mxREAL);
    mxWrapCopy_int(plhs[3], out3_, dim7_);

mw_err_label:
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (out3_) mxFree(out3_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- gluttonfit.mw: 84 ----
 * int keep = minisgammaloc(int[] jt, int[] l, double[] val, double[] tsh, int N, int j, double gamma);
 */
const char* stubids4_ = "o int = minisgammaloc(i int[], i int[], i double[], i double[], i int, i int, i double)";

void mexStub4(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* jt         */
    int*        in1_ =0; /* l          */
    double*     in2_ =0; /* val        */
    double*     in3_ =0; /* tsh        */
    int         in4_;    /* N          */
    int         in5_;    /* j          */
    double      in6_;    /* gamma      */
    int         out0_;   /* keep       */

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[4]++;
    out0_ = minisgammaloc(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- gluttonfit.mw: 114 ----
 * gluttonstuffme(double[] W, int M, int T, int K, int fac, inout double[] Y, int Nt, double tpad, double eta, int skip, double gamma, double[] nlps, output double[maxNs] t, output int[maxNs] l, output double[maxNs] a, output int[1] Ns, int maxNs, int verb);
 */
const char* stubids5_ = "gluttonstuffme(i double[], i int, i int, i int, i int, io double[], i int, i double, i double, i int, i double, i double[], o double[x], o int[x], o double[x], o int[x], i int, i int)";

void mexStub5(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* W          */
    int         in1_;    /* M          */
    int         in2_;    /* T          */
    int         in3_;    /* K          */
    int         in4_;    /* fac        */
    double*     in5_ =0; /* Y          */
    int         in6_;    /* Nt         */
    double      in7_;    /* tpad       */
    double      in8_;    /* eta        */
    int         in9_;    /* skip       */
    double      in10_;    /* gamma      */
    double*     in11_ =0; /* nlps       */
    int         in12_;    /* maxNs      */
    int         in13_;    /* verb       */
    double*     out1_=0; /* t          */
    int*        out2_=0; /* l          */
    double*     out3_=0; /* a          */
    int*        out4_=0; /* Ns         */
    mwSize      dim14_;   /* maxNs      */
    mwSize      dim15_;   /* maxNs      */
    mwSize      dim16_;   /* maxNs      */
    mwSize      dim17_;   /* 1          */

    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    in6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in8_ = (double) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in10_ = (double) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[11])*mxGetN(prhs[11]) != 0) {
        in11_ = mxGetPr(prhs[11]);
    } else
        in11_ = NULL;
    in12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    out1_ = (double*) mxMalloc(dim14_*sizeof(double));
    out2_ = (int*) mxMalloc(dim15_*sizeof(int));
    out3_ = (double*) mxMalloc(dim16_*sizeof(double));
    out4_ = (int*) mxMalloc(dim17_*sizeof(int));
    if (mexprofrecord_)
        mexprofrecord_[5]++;
    gluttonstuffme(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, in10_, in11_, out1_, out2_, out3_, out4_, in12_, in13_);
    plhs[0] = mxCreateDoubleMatrix(mxGetM(prhs[5]), mxGetN(prhs[5]), mxREAL);
    mxWrapCopy_double(plhs[0], in5_, mxGetM(prhs[5])*mxGetN(prhs[5]));
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], out1_, dim14_);
    plhs[2] = mxCreateDoubleMatrix(dim15_, 1, mxREAL);
    mxWrapCopy_int(plhs[2], out2_, dim15_);
    plhs[3] = mxCreateDoubleMatrix(dim16_, 1, mxREAL);
    mxWrapCopy_double(plhs[3], out3_, dim16_);
    plhs[4] = mxCreateDoubleMatrix(dim17_, 1, mxREAL);
    mxWrapCopy_int(plhs[4], out4_, dim17_);

mw_err_label:
    if (in5_)  mxFree(in5_);
    if (out1_) mxFree(out1_);
    if (out2_) mxFree(out2_);
    if (out3_) mxFree(out3_);
    if (out4_) mxFree(out4_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- gluttonfit.mw: 156 ----
 * multiglutton(double[] W, int M, int T, int K, int fac, inout double[] Y, int Nt, double tpad, double eta, int skip, double gamma, double[] nlps, output double[maxNs] t, output int[maxNs] l, output double[maxNs] a, output int[1] Ns, output double[M, Nt] R, int wantR, int verb);
 */
const char* stubids6_ = "multiglutton(i double[], i int, i int, i int, i int, io double[], i int, i double, i double, i int, i double, i double[], o double[x], o int[x], o double[x], o int[x], o double[xx], i int, i int)";

void mexStub6(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* W          */
    int         in1_;    /* M          */
    int         in2_;    /* T          */
    int         in3_;    /* K          */
    int         in4_;    /* fac        */
    double*     in5_ =0; /* Y          */
    int         in6_;    /* Nt         */
    double      in7_;    /* tpad       */
    double      in8_;    /* eta        */
    int         in9_;    /* skip       */
    double      in10_;    /* gamma      */
    double*     in11_ =0; /* nlps       */
    int         in12_;    /* wantR      */
    int         in13_;    /* verb       */
    double*     out1_=0; /* t          */
    int*        out2_=0; /* l          */
    double*     out3_=0; /* a          */
    int*        out4_=0; /* Ns         */
    double*     out5_=0; /* R          */
    mwSize      dim14_;   /* maxNs      */
    mwSize      dim15_;   /* maxNs      */
    mwSize      dim16_;   /* maxNs      */
    mwSize      dim17_;   /* 1          */
    mwSize      dim18_;   /* M          */
    mwSize      dim19_;   /* Nt         */

    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    in6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in8_ = (double) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in10_ = (double) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[11])*mxGetN(prhs[11]) != 0) {
        in11_ = mxGetPr(prhs[11]);
    } else
        in11_ = NULL;
    in12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    out1_ = (double*) mxMalloc(dim14_*sizeof(double));
    out2_ = (int*) mxMalloc(dim15_*sizeof(int));
    out3_ = (double*) mxMalloc(dim16_*sizeof(double));
    out4_ = (int*) mxMalloc(dim17_*sizeof(int));
    out5_ = (double*) mxMalloc(dim18_*dim19_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[6]++;
    multiglutton(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, in10_, in11_, out1_, out2_, out3_, out4_, out5_, in12_, in13_);
    plhs[0] = mxCreateDoubleMatrix(mxGetM(prhs[5]), mxGetN(prhs[5]), mxREAL);
    mxWrapCopy_double(plhs[0], in5_, mxGetM(prhs[5])*mxGetN(prhs[5]));
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], out1_, dim14_);
    plhs[2] = mxCreateDoubleMatrix(dim15_, 1, mxREAL);
    mxWrapCopy_int(plhs[2], out2_, dim15_);
    plhs[3] = mxCreateDoubleMatrix(dim16_, 1, mxREAL);
    mxWrapCopy_double(plhs[3], out3_, dim16_);
    plhs[4] = mxCreateDoubleMatrix(dim17_, 1, mxREAL);
    mxWrapCopy_int(plhs[4], out4_, dim17_);
    plhs[5] = mxCreateDoubleMatrix(dim18_, dim19_, mxREAL);
    mxWrapCopy_double(plhs[5], out5_, dim18_*dim19_);

mw_err_label:
    if (in5_)  mxFree(in5_);
    if (out1_) mxFree(out1_);
    if (out2_) mxFree(out2_);
    if (out3_) mxFree(out3_);
    if (out4_) mxFree(out4_);
    if (out5_) mxFree(out5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[512];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }

    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids4_) == 0)
        mexStub4(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids5_) == 0)
        mexStub5(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids6_) == 0)
        mexStub6(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(7 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 7 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to gluttonfit.mw:34\n", mexprofrecord_[1]);
        mexPrintf("%d calls to gluttonfit.mw:37\n", mexprofrecord_[2]);
        mexPrintf("%d calls to gluttonfit.mw:59\n", mexprofrecord_[3]);
        mexPrintf("%d calls to gluttonfit.mw:84\n", mexprofrecord_[4]);
        mexPrintf("%d calls to gluttonfit.mw:114\n", mexprofrecord_[5]);
        mexPrintf("%d calls to gluttonfit.mw:156\n", mexprofrecord_[6]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to gluttonfit.mw:34\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to gluttonfit.mw:37\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to gluttonfit.mw:59\n", mexprofrecord_[3]);
        fprintf(logfp, "%d calls to gluttonfit.mw:84\n", mexprofrecord_[4]);
        fprintf(logfp, "%d calls to gluttonfit.mw:114\n", mexprofrecord_[5]);
        fprintf(logfp, "%d calls to gluttonfit.mw:156\n", mexprofrecord_[6]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

